apiVersion: skaffold/v2beta6
kind: Config
build:
    artifacts:
        - image: fujeffrey1/ticketing-auth
          context: auth
          sync:
              manual:
                  - src: "src/**/*.ts"
                    dest: .
          docker:
              dockerfile: Dockerfile
        - image: fujeffrey1/ticketing-client
          context: client
          sync:
              manual:
                  - src: "**/*.js"
                    dest: .
          docker:
              dockerfile: Dockerfile
        - image: fujeffrey1/ticketing-tickets
          context: tickets
          sync:
              manual:
                  - src: "src/**/*.ts"
                    dest: .
          docker:
              dockerfile: Dockerfile
        - image: fujeffrey1/ticketing-orders
          context: orders
          sync:
              manual:
                  - src: "src/**/*.ts"
                    dest: .
          docker:
              dockerfile: Dockerfile
        - image: fujeffrey1/ticketing-expiration
          context: expiration
          sync:
              manual:
                  - src: "src/**/*.ts"
                    dest: .
          docker:
              dockerfile: Dockerfile
        - image: fujeffrey1/ticketing-payments
          context: payments
          sync:
              manual:
                  - src: "src/**/*.ts"
                    dest: .
          docker:
              dockerfile: Dockerfile
    local:
        push: false
deploy:
    kubectl:
        manifests:
            - ./infrastructure/k8s/*
